import LegalShell from '../components/LegalShell';

export default function Terms() {
  return (
    <LegalShell
      title="Terms of Service"
      lastUpdated="18 November, 2025"
    >
      <div className="callout-warning">
        <p><strong>IMPORTANT:</strong> By using FastTrackr AI's services, you acknowledge that you have read, understood, and agree to be bound by this Agreement. If you do not agree with these terms, do not use the Services.</p>
      </div>
      <p>FASTTRACKR INC. (&ldquo;FastTrackr AI&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo; or &ldquo;our&rdquo;) is willing to provide certain software and services to you as the individual, the company, or the legal entity (referenced below as &ldquo;you&rdquo; or &ldquo;your&rdquo; or &ldquo;Customer&rdquo;) that enters into a written or online order, written or online registration form or similar document with FastTrackr AI that references these terms and conditions only on the condition that you accept all of these terms and conditions (&ldquo;Agreement&rdquo;).</p>

      <h2>1. Definitions</h2>
      <p><strong>1.1 Affiliates</strong> — any company, partnership or other entity now existing or hereafter organized that directly or indirectly controls, is controlled by or under common control with a Party.</p>
      <p><strong>1.2 AI or &ldquo;Artificial Intelligence&rdquo;</strong> — any system, platform or tool designed to operate with a level of autonomy, taking inputs and using algorithmic, mathematical or modeling techniques (such as machine learning) to generate output.</p>
      <p><strong>1.3 AI Output</strong> — the Meeting Notes, Tasks, Insights, CRM Updates, and other outputs generated by the Platform on behalf of Customer.</p>
      <p><strong>1.4 Confidential Information</strong> — has the meaning given to it in Section 4.1.</p>
      <p><strong>1.5 Customer Data</strong> — all data and content made available by the Customer or its Users to FastTrackr AI or otherwise provided in connection with the provision of the Services.</p>
      <p><strong>1.6 Documentation</strong> — the documentation for the Platform generally made available by FastTrackr AI to its customers.</p>
      <p><strong>1.7 Effective Date</strong> — the date that the first Order Form is entered into between the Parties referencing this Agreement or when a user first accesses the platform.</p>
      <p><strong>1.8 Meeting Notes</strong> — a summary of a meeting produced by the Platform.</p>
      <p><strong>1.9 Order Form</strong> — each FastTrackr AI ordering document or electronic subscription selection process completed on FastTrackr AI's website when a user selects a paid subscription plan.</p>
      <p><strong>1.10 Authentication</strong> — the process by which users log in to the Platform, accomplished primarily through Gmail and Outlook authentication systems.</p>
      <p><strong>1.11 Connected Applications</strong> — third-party applications that connect to or interoperate with the Platform, including but not limited to Zoom, Microsoft Teams, Google Meet, Gmail, Outlook, and various CRM systems.</p>
      <p><strong>1.12 Services</strong> — the Platform and any technical support services described in this Agreement.</p>
      <p><strong>1.13 Platform</strong> — FastTrackr AI's proprietary AI-powered SaaS platform for financial advisors, including AI-powered meeting support, task management, insight generation, and CRM automation. Does not include the Document Processing Module by default.</p>
      <p><strong>1.14 Users</strong> — any employee or independent contractor of the Customer that have been provided with permission to use the Platform.</p>
      <p><strong>1.15 Document Processing Module</strong> — the optional service feature that allows Users to upload, process, and analyze financial and non-financial documents through the Platform.</p>
      <p><strong>1.16 Financial Documents</strong> — documents containing financial information uploaded through the Document Processing Module.</p>
      <p><strong>1.17 Sensitive Documents</strong> — documents containing highly confidential information including identification documents, will statements, trust documents, and documents containing social security numbers or other PII.</p>
      <p><strong>1.18 Document Data</strong> — information extracted, analyzed, or derived from documents uploaded through the Document Processing Module.</p>
      <p><strong>1.19 Document Analysis Output</strong> — insights, summaries, extractions, and analyses generated by the Platform from uploaded documents.</p>
      <p><strong>1.20 Free Tier</strong> — the no-cost access to the Platform, which may have limited features or usage restrictions.</p>

      <h2>2. Services</h2>
      <p><strong>2.1 Services.</strong> FastTrackr AI shall provide the Customer with the specific Services specified on an Order Form or, for Free Tier users, the Services made available without charge.</p>
      <p>This Service is designed exclusively for the United States market. The Platform is intended for use by financial advisors and professionals operating within the United States.</p>
      <p>The Services are not tailored to comply with HIPAA or FISMA. You may not use the Services in a way that would violate the Gramm-Leach-Bliley Act (GLBA).</p>

      <h3>2.1.1 Document Processing Module (Optional Service)</h3>
      <p>The Document Processing Module is optional and not included by default. Customer may opt in:</p>
      <ul>
        <li>During initial onboarding by notifying the FastTrackr AI team</li>
        <li>At any time by contacting <a href="mailto:contact@fasttrackr.ai">contact@fasttrackr.ai</a></li>
        <li>Through email confirmation sent by FastTrackr AI</li>
      </ul>
      <p>Supported document types include: brokerage statements, bank statements, tax forms, equity compensation statements, identification documents, will statements, trust documents, and benefit plan documents.</p>
      <p><strong>Opting Out.</strong> Customer may opt out at any time by writing to <a href="mailto:contact@fasttrackr.ai">contact@fasttrackr.ai</a>. All documents and Document Data will be deleted within 90 days of the opt-out request.</p>

      <p><strong>2.2 License Grant.</strong> FastTrackr AI grants Customer a non-exclusive, non-transferable license to access and use the Platform solely for internal business purposes during the term of the applicable Order Form.</p>
      <p><strong>2.3 Fair Usage Policy.</strong> FastTrackr AI reserves the right to monitor Customer's usage and may contact Customer if usage significantly exceeds average usage of other customers.</p>
      <p><strong>2.4 Use by Affiliates.</strong> Customer may make the Platform available to its Affiliates provided that all licensing restrictions are complied with.</p>
      <p><strong>2.5 Connected Applications.</strong> Customer is responsible for maintaining its own subscriptions for Connected Applications. FastTrackr AI shall not be responsible for any issues caused directly by Connected Applications.</p>
      <p><strong>2.6 Beta Services.</strong> FastTrackr AI may make modules available for up to 30 days for evaluation. Unless terminated prior to expiry, the subscription automatically continues.</p>

      <h2>3. Fees; payment terms</h2>
      <p><strong>Free Tier.</strong> FastTrackr AI offers a Free Tier with certain features at no charge. FastTrackr AI reserves the right to modify, suspend, or discontinue the Free Tier at any time.</p>
      <p><strong>3.1 Fees.</strong> Customer shall pay all fees specified in Order Forms. Fees are quoted in US dollars, non-cancelable, and non-refundable.</p>
      <p><strong>3.2 Late Fees.</strong> Unpaid charges may accrue late interest at 1.5% per month or the maximum rate permitted by law.</p>
      <p><strong>3.3 Taxes.</strong> Unless otherwise stated, fees do not include taxes. Customer is responsible for all applicable taxes.</p>
      <p><strong>3.4 Disputed Charges.</strong> Customer may dispute charges in writing on or before the due date. Undisputed amounts must still be paid.</p>

      <h2>4. Confidentiality</h2>
      <p><strong>4.1 Confidential Information.</strong> Each Party shall hold the other's Confidential Information in confidence and use it only for purposes of this Agreement. Customer Data and AI Output shall be deemed Customer's Confidential Information.</p>
      <p><strong>4.2 Exclusions.</strong> Information is not Confidential if it was already known, becomes publicly available, is independently developed, or must be disclosed by law.</p>
      <p><strong>4.3 Injunctive Relief.</strong> Either party may seek injunctive relief for unauthorized use of Confidential Information.</p>

      <h2>5. Warranties</h2>
      <p><strong>5.1 Availability.</strong> FastTrackr AI will use commercially reasonable efforts to make the Platform available 24/7. Scheduled maintenance requires 48 hours' notice.</p>
      <p><strong>5.2 Platform Warranty.</strong> FastTrackr AI warrants the Platform will conform with its descriptions in all material respects. No warranty for features provided by third parties.</p>
      <p><strong>5.3 Authentication and Account Security.</strong> Customer is responsible for maintaining confidentiality of authentication credentials and for notifying FastTrackr AI of any unauthorized access.</p>
      <p><strong>5.4 Data Security.</strong> FastTrackr AI uses industry-standard safeguards including AES 256 encryption.</p>
      <p><strong>5.5 No Other Warranty.</strong> THE PLATFORM IS PROVIDED &ldquo;AS IS.&rdquo; FASTTRACKR AI DISCLAIMS ALL WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.</p>
      <p><strong>5.6 AI Output Warranty Disclaimer.</strong> AI output may contain errors or inconsistencies. Customer is solely responsible for reviewing AI output before use.</p>
      <p><strong>5.7 Financial Advice Disclaimer.</strong> The Platform and AI output are NOT intended to provide financial, investment, legal, tax, or other professional advice.</p>
      <p><strong>5.8 Regulatory Compliance Disclaimer.</strong> FastTrackr AI does not warrant compliance with SEC, FINRA, or other financial regulations. Customer is solely responsible for regulatory compliance.</p>
      <h3>5.9 Document Processing Module disclaimers</h3>
      <ul>
        <li><strong>5.9.1</strong> Document analysis may contain errors. Customer must verify all Document Data before reliance.</li>
        <li><strong>5.9.2</strong> Customer must obtain all necessary consents from document owners before uploading.</li>
        <li><strong>5.9.3</strong> Documents may contain sensitive information including SSNs. Customer assumes all risk.</li>
        <li><strong>5.9.4</strong> Document Analysis Output is not professional advice.</li>
        <li><strong>5.9.5</strong> FastTrackr AI does not warrant compliance with regulatory record-keeping requirements. Customer must maintain their own records.</li>
        <li><strong>5.9.6</strong> No method of electronic storage is 100% secure. Customer assumes risk of uploading sensitive documents.</li>
      </ul>

      <h2>6. Limitation of liability</h2>
      <p><strong>6.1 Limitation.</strong> Neither party will be liable for indirect, incidental, consequential, or special damages. Each party's aggregate liability is limited to the total amount paid by Customer in the 12 months preceding the claim.</p>

      <h2>7. Term and updates to terms</h2>
      <p><strong>7.1 Term.</strong> This Agreement commences on the Effective Date and continues until terminated. Order Forms auto-renew monthly or annually unless cancelled with 15 days' notice.</p>
      <p><strong>7.1.1 Updates to Terms.</strong> FastTrackr AI may modify this Agreement at any time. Continued use constitutes acceptance.</p>
      <p><strong>7.2 Termination.</strong> Either Party may terminate for material breach not cured within 30 days of written notice, or if the other Party becomes insolvent.</p>
      <p><strong>7.3 Effect of Termination.</strong> Upon termination, FastTrackr AI will cease providing Services. Customer shall pay all accrued fees. Data access and deletion timelines apply per Section 8.8.</p>

      <h2>8. Ownership; additional obligations</h2>
      <p><strong>8.1 Platform and Intellectual Property.</strong> All right, title and interest in the Platform remain with FastTrackr AI. Customer must not use FastTrackr AI's name, logo, or trademarks without prior written consent.</p>
      <p><strong>8.2 AI Models.</strong> FastTrackr AI does not use Customer Data, AI Output, Document Data, or Document Analysis Output to train or refine its own AI models. Third-party LLM/AI services are contractually required not to use Customer data for training.</p>
      <p><strong>8.3 Customer Data.</strong> Customer retains ownership of all Customer Data and grants FastTrackr AI a limited license to use it solely to provide the Platform.</p>
      <p><strong>8.4 Customer Obligations.</strong> Customer is responsible for: User activities, obtaining meeting participant consents, compliance with all applicable laws, and (if using the Document Processing Module) obtaining document owner consents.</p>
      <p><strong>8.5 AI Output.</strong> Excluding FastTrackr AI IP, Customer owns all AI Output generated via the Platform.</p>
      <p><strong>8.6 Intellectual Property Rights.</strong> All IP in the Platform remains with FastTrackr AI.</p>
      <p><strong>8.7 Suggestions.</strong> FastTrackr AI has a perpetual, royalty-free license to use any feedback provided by Customer.</p>

      <h3>8.8 Data retention, backup and deletion</h3>
      <table>
        <thead>
          <tr>
            <th>AI Output</th>
            <th>Retention</th>
            <th>Backup</th>
          </tr>
        </thead>
        <tbody>
          <tr><td>Meeting Notes</td><td>Indefinitely unless deletion requested</td><td>Backed up by FastTrackr AI</td></tr>
          <tr><td>Tasks</td><td>Indefinitely unless deletion requested</td><td>Backed up by FastTrackr AI</td></tr>
          <tr><td>Insights and Summaries</td><td>Indefinitely unless deletion requested</td><td>Backed up by FastTrackr AI</td></tr>
          <tr><td>CRM Updates</td><td>Indefinitely unless deletion requested</td><td>Backed up by FastTrackr AI</td></tr>
          <tr><td>Meeting Recording Audio</td><td>Up to 7 days from creation, then deleted</td><td>Backed up during retention period</td></tr>
          <tr><td>Uploaded Documents (Doc Processing Module)</td><td>Duration of active subscription; deleted within 90 days of opt-out, deletion request, or termination</td><td>May be backed up during retention period</td></tr>
        </tbody>
      </table>
      <p>All backups retained for 60 days unless required by applicable law.</p>
      <p>Document deletion requests: <a href="mailto:contact@fasttrackr.ai">contact@fasttrackr.ai</a>.</p>

      <h2>9. Dispute resolution</h2>
      <p><strong>9.1 Disclaimer of Indemnification.</strong> Neither party shall have any obligation to indemnify the other party.</p>
      <p><strong>9.2 Arbitration.</strong> Disputes shall be settled by binding arbitration under AAA rules. Place of arbitration: Delaware, United States. Language: English.</p>
      <p><strong>9.3 Force Majeure.</strong> Neither party is liable for delays caused by events beyond reasonable control. If a Force Majeure Event continues for 60+ consecutive days, either party may terminate.</p>
      <p><strong>Data Breach Notification.</strong> FastTrackr AI shall notify Customer within 72 hours of becoming aware of a data breach affecting Customer Data.</p>

      <h2>Questions, concerns, or complaints</h2>
      <ul>
        <li><strong>Email:</strong> <a href="mailto:contact@fasttrackr.ai">contact@fasttrackr.ai</a></li>
        <li><strong>Web:</strong> <a href="/contact">fasttrackr.ai/contact</a></li>
      </ul>
    </LegalShell>
  );
}
